sudo: false
language: java
notifications:
  email:
    - lada.dvorak7@gmail.com
    
jdk:
  - openjdk11

env:

  matrix:
    - WELD_VERSION=3.0.5.Final

  global:
    # SONATYPE
    - secure: "WkSh9OeKNC1YZKiQTtfONWwHr+Y3e//URAjlbvmzig2eEMJHeQO/1ZXpvxSFDAhYDfDUFE2sCdTlO8s4cDF8/7+ZCzcvCj/ZeUUQYEf6KRCrkn1awVo+VBBVyJPN80j67oVBN3zipkRXRkxU5lMyHZkABH+722/9YhGcZvg3BIHGPKRvHrZfN61LJirpsyJ0hN6okX1pqyibWiVOsq324vXXZ8Z1kdubH6KIqA6w4uX6IZ9HtOJKe570NXE13xxXIHJ4oO+g1is8w4j8axjLkoX+5ZaIo3tSmmVTNE1oCOLulkAxwis5t4+w4lkGFqOkOrvrWkkch0IrnmNAbP5WVdC/9ILemwF09qiVb9cnNPykRbLwMHFrlDzP+nyMk4ecXbWq1FhLj/WqpdJAk3s8RgZVFwX6R8DQFVk5tCDnycKuM8HSxxNYE35KRcBAxh/9YL88wkufGt7BtrflCg6eG+Hkk+SQE4FHd7xW07YyODn/RhA6s0yF8x2g76zAkvYlLd7xbigApnmmA80fcJP0lDKDOHNVGsX/2VU/ucHq5/DaqsT3A/AlrFz3YwjHf1XG4w+Dl8l38im19OW6dxrqSEaucrECm94muXhfvs0GnIcdmPrfeWX43LHx7XItcK3/hp/iG09DuUVvbLIe75iFkmI2CSxOQpCFJpb8qOTCTdg="
    - secure: "aXfkaGzi80Uaa93pCnhIw5xMjaBhL9k5ArOZwgeKeK5mey1Tt5ttump8LuP/kb7rToauzUr8Su6YeaMZgFhUf+oZNOZ8giq4OO+qsnXAudLROMGEYrPnbC03YalCcsThDRQua6//U3Z3abG0TSS227peQaGgFJn26itRuoZd5WalWXOfCWaxrSCljmEHNJui1UnNwRFYKETw/QdsCbd2C0SO0nT/85hxKy50RwujDbgHMfZsW6o5YpAZbkUchYtON1vkCNc2G1sH4EPLci5zsgPDn6THoznqXBc4byOUtYHPPA2852TW52YtzhUgwyNxP42mJGGlgoH+3Df6FnK+8jLDLpHQAHpJeqndB67bO6KzyWuO8YLsAzHbnWJUbOIJxrb2/pBsn3z8ImM9NQMNuShJXbatNw5iIdr+/+RQiBUsNwPsAJJ42iybjufLouC+xJL+zmDnLygFmy2Y6O3uR6oRa3E+rQscWdKvOplpKgf6hPjoy44y147IJzHDbHUCnBHt8vg2Vy7zT+pM+Uvb4kESwl0NDbEDE3X3tWT7JeRZmF2GWOsSnPK8XDr/EO0QlNFwJ+SN6CYYPME8CxnD0iSO90CThiquHpT4GfvIep88UMTbu3WbmqYA2XKvPzaCWZrgZQ9q1TumYNtqHfVdRX8HcPm+o2VK0+7RBOJ1ciA="
   

script: "mvn clean install -DskipTests"
deploy:
  - provider: script
    script: ./.travis.deploy.sh
    skip_cleanup: true
    on:
      branch: master
